# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bc22ba9c9cc8262aa45226e50b0b97e809b9138d4750b8b7f96a30630134760b49480d5e63954f96aea5e4780d77a528bddb53854a02247d3dc651d85936ab0c

test:
  secret_key_base: 75aacad14a77f7764f88d433e5a35bbac22d14d5ea3938791eb39c2b0bcc45a553cb3e7887c06c7569cebef27bfb58eb257cc437466e2d29ccbc40aa0094a069

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
